# Generated by Django 3.2.4 on 2021-06-19 14:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('authors', models.CharField(max_length=256)),
                ('published_date', models.CharField(max_length=4)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), size=None)),
                ('average_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('ratings_count', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
